graph TB

   subgraph Shell
   contacts[Contact manager micro-frontend<br />https://app.com/contacts]
   organization[Organization manager micro-frontend<br />https://app.com/organization]
   other[...]
   end